### ISSUE TITLE
An easier approach?

### ISSUE THREAD

**Issue by rbreaves** [petrstepanov/gnome-macos-remap#1]
So this isn’t really an issue but I’ve found an app called xkeysnail that I think makes what you or I are trying to do here a lot easier.

https://github.com/mooz/xkeysnail

I’m currently using it in the dev branch of Kinto.sh & would happily merge any PRs or add features to either Kinto or even xkeysnail (assuming the maintainer continues to accept my PRs).
https://github.com/rbreaves/kinto

**Comment by petrstepanov** [comment]
Hi Ben, thanks for referring Kinto. I will definitely check it out one day.
