### ISSUE TITLE
Pop!_OS. Failed to set RT scheduler: Operation not permitted

### ISSUE THREAD

**Issue by rxng** [petrstepanov/gnome-macos-remap#11]
Running install.sh on popos, a warning appears with the following 

```
Flipping Super and Control keys...
Copying AutoKey Phrases...
Changing default GNOME keybindings...

** (process:126525): WARNING **: 20:38:01.298: Failed to set RT scheduler: Operation not permitted
```

Is the RT scheduler warning an issue? What is the fix?

**Comment by petrstepanov** [comment]
Hi, this is an issue with Pop!_OS distribution. At the moment PoP!_OS uses a modified version of GNOME 3.38. For some reason the warning is output when executing `gnome-shell --version` command in PoP!_OS only. Warning is not present in distributions with unmodified GNOME version (Fedora, Arch). It is clearly a PoP!_OS issue and it has been reported in a [few other scripts](https://github.com/pop-os/shell/issues/385). Maybe this warning will be addressed in a new PoP!_OS version.

Moreover, the warning does not seem to affect the installation script workflow.

**Comment by illtellyoulater** [comment]
This also happens while using the Orchis theme install script (install.sh):

https://github.com/vinceliuice/Orchis-theme
