### ISSUE TITLE
Logitech MX Keys Keyboard

### ISSUE THREAD

**Issue by rxng** [petrstepanov/gnome-macos-remap#12]
I installed this but it is functioning weirdly and not like a mac.

In your remap, super has become the 1st key, and control has become the 2nd key. 
Making it: CMD - Ctrl - Alt 

This is different to a mac, where it is supposed to be:
Ctrl - Opt - CMD

Am I missing something?

**Comment by petrstepanov** [comment]
Hi, it seems that you are using a PC style keyboard. This script is designed for Apple keyboard. Looking forward to hearing from you!

**Comment by rxng** [comment]
![874D20CD-C9C1-4A50-B223-50A2B29BDDBD](https://user-images.githubusercontent.com/19649766/127668787-408f271e-2ccc-43be-9aa3-32b03f979710.jpeg)

Yes I am using Logitech mx keys, is there a way to modify the remap so that it supports windows style? Shouldn’t be a big mod?

**Comment by petrstepanov** [comment]
Hi, your keyboard supports two layouts - macOS and Windows. It seems that your keyboard layout defaults to Windows style when running Linux. One of the solutions would be to install [Solaar](https://pwr-solaar.github.io/Solaar/) and force your keyboard to use macOS layout (refer to the image below).

![solaar0](https://user-images.githubusercontent.com/859814/127751873-953ba284-a6a1-4597-ac4d-9dcb38989783.png)

Let me know how's it going!

**Comment by rxng** [comment]
hey @petrstepanov your suggestion of using solaar to force the keyboard to use macOS layout is awesome, I can't believe I tried everything except that! Perhaps something to put in the readme for others who use logitech also to benefit ?

**Comment by gabriellovate** [comment]
I have a similar situation, but unfortunately solaar doesn't work for me. I have a custom keyboard with Windows layout but the keycaps have a macOS layout. Any tips on how to swap `alt` and `cmd` to fix it for a generic keyboard?
