### ISSUE TITLE
Error during installation using recommended commands on Pop!_OS 21.04

### ISSUE THREAD

**Issue by cstrouse** [petrstepanov/gnome-macos-remap#14]
When executing the installation script via `sh install.sh` as recommended in the readme I run into the below error. Running the script using bash works properly. This is on `Pop!_OS 21.04` which symlinks `sh` to `dash` so it may only affect this distro.

```
casey@pop-os:~/Downloads/gnome-macos-remap$ sh install.sh 
Flipping Super and Control keys...
[sudo] password for casey: 
Copying AutoKey Phrases...
Changing default GNOME keybindings...
install.sh: 54: [[: not found

Almost there! Please do following:
1. Open 'autokey-gtk'.
   In Edit -> Preferences select 'Automatically start AutoKey at login'.
2. Restart your computer.
3. On the login screen under the gear icon on the bottom right select 'GNOME on Xorg'.
4. Enjoy!
```

**Comment by petrstepanov** [comment]
Thanks for reporting this. I pushed a tweak. Please note that  `Failed to set RT scheduler` [warning message will show up](https://github.com/petrstepanov/gnome-macos-remap/issues/11) during the installation. This is normal.
