### ISSUE TITLE
error while installing 

### ISSUE THREAD

**Issue by oefterdal** [petrstepanov/gnome-macos-remap#17]
oefterdal@ghost:~/Downloads/gnome-macos-remap$ sh install.sh 
Copying AutoKey Phrases...
Backing up /usr/share/X11/xkb/symbols/pc...
Flipping Super and Control keys...
Changing default GNOME keybindings...
**./bin/install-dconf.sh: 40: [[: not found
./bin/install-dconf.sh: 41: Bad substitution**

Almost there! Please do following:
1. Open 'autokey-gtk'. Go to Edit -> Preferences.
   Select 'Automatically start AutoKey at login'.
2. Restart your computer.
3. On the login screen click the gear icon on the bottom right.
   Select 'GNOME on Xorg'. Login.
4. Enjoy!

**Comment by petrstepanov** [comment]
Hi, thanks for reporting. I probably broke it yesterday with some updates. Will look later today.

**Comment by petrstepanov** [comment]
Could you please provide the OS and desktop environment you are using?

**Comment by oefterdal** [comment]
Ubuntu 20.04 LTS with Gnome. Its a vanilla install, this is the first thing I installed.

**Comment by oefterdal** [comment]
I manged to install it, I just removed the if checks and the 40 and 41 specific settings so no rush :)

**Comment by petrstepanov** [comment]
Ok. Looks like some schema incompatibility. Will check later.

**Comment by petrstepanov** [comment]
Hi! I just pushed the fix and tested on Ubuntu 20.04 and 21.10. Thanks again for reporting. I'm closing the Issue now.
