### ISSUE TITLE
search in nano

### ISSUE THREAD

**Issue by oefterdal** [petrstepanov/gnome-macos-remap#19]
In nano ctrl+w is search, but that closes the window, does the same happen for you?

**Comment by petrstepanov** [comment]
Hi Øystein,

Thank you for reporting this bug. I just pushed a workaround for it. Default Autokey phrase is replaced with a Python script now. Now this user scenario provides expected result. However the downside of using Python scripts is a little delay before action takes place.

Can you please download the updated version of the remap, re-install and confirm if everything works?

**Comment by oefterdal** [comment]
Didn't work for me.

**Comment by petrstepanov** [comment]
Interestng. Do you want to hop on a quick Zoom call to narrow it down?

**Comment by oefterdal** [comment]
Yes, can do that.

**Comment by oefterdal** [comment]
Works
