### ISSUE TITLE
Alt+Backspace deletes the word

### ISSUE THREAD

**Issue by igorlvicente** [petrstepanov/gnome-macos-remap#20]
On macOS, when I press `Alt`+`Backspace`, the word gets deleted. How can I add this?

PS: Nice repo and thanks for the work done.

**Comment by petrstepanov** [comment]
Hi, I just pushed the change. Can you please check out, reinstall and confirm if it works as intended?

**Comment by igorlvicente** [comment]
Yeah, it seems to be working. Awesome. Thanks, @petrstepanov.
