### ISSUE TITLE
how to use this for non apple keyboards

### ISSUE THREAD

**Issue by edoardoc** [petrstepanov/gnome-macos-remap#22]
Hello!
so this is not really an issue, this project is the only concrete attempt in simplifying the usage of Linux for ppl that [got used to / still are using] a mac 
well done! 

one thing I am finding difficult to understand is: now that the beloved CMD is mapped to SUPER(aka win key) in linux terminology, perfect for an apple Keyboard of course;
...but how should I go to use this in those keyboards were the first key on the left of the space bar is ALT ? muscle memory is always hitting ALT+C / ALT+V for a copy and paste
thanks

**Comment by edoardoc** [comment]
found in previous issues this one which sheds some light:

https://github.com/petrstepanov/gnome-macos-remap/issues/15

so closing this issue

**Comment by petrstepanov** [comment]
Glad you figured it out!

**Comment by edoardoc** [comment]
yes those 3 options that you mention:

1) You can modify the /usr/share/X11/xkb/symbols/pc file.
2) If using GNOME desktop environment, install and open GNOME Tweaks app. Go to "Keyboard & Mouse" > "Additional Layout Options" > "Alt and Win behavior" > "Alt is swapped with Win".
3) Finally you can simply use Autokey app to remap a particular combination "Super + V" to "Alt +V".

I tried no.2 only, but I found that there are already a couple of switches on and - at least  for me - when I was swapping Alt and Win nothing would work anymore... 
as far as no. 1 and 3, its as if I needed to do it from the beginning, so I am currently using another prj.
Tbh your solution is the most elegant one but is currently applicable only for apple keyboards connected to desktops or for anyone that would install linux on apple hw / mac.
