### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by DivineEssentia** [petrstepanov/gnome-macos-remap#27]
I installed this, but i couldnt use ctrl, so i tried to go back. Now, super and ctrl are both mapped to ctrl and i can’t fix it. What should I do?

**Comment by petrstepanov** [comment]
Hi, did you try uninstalling the script? https://github.com/petrstepanov/gnome-macos-remap#how-to-uninstall

**Comment by DivineEssentia** [comment]
I got it fixed. Because I’m using a theme that requires wayland, I used the super buggy wayland script. I didn’t realize that the uninstall script for that one didn’t remove the service for the gnome macOS remap. So I removed that and it’s back to normal again :D

**Comment by petrstepanov** [comment]
Oh ok. This remap does not work with Wayland at all. There seem to be some [bugs in Wayland that still need to be resolved](https://github.com/petrstepanov/gnome-macos-remap/issues/7) before we can make it work.

Regarding the service. This script does not install any systemd services 🤔. I'm glad you got it sorted out!
