### ISSUE TITLE
I cant uninstall

### ISSUE THREAD

**Issue by BerkanSezer** [petrstepanov/gnome-macos-remap#4]
I installed with `install.sh` and something happened i dont want.
I run the `uninstall.sh` file and reboot the os, nothing changed. my windows button changed with CTRL button and i cant reverse it. 
Please help, thanks

**Comment by petrstepanov** [comment]
Hi, you can manually revert changes for the CTRL/SUPER key swap in the file below:
```
sudo nano /usr/share/X11/xkb/symbols/pc
```
Please modify the lines #26 and #27 to reflect:
```
    key <LCTL> {        [ Control_L               ]       };
    key <LWIN> {        [ Super_L             ]       };
```
Also lines #30 and #31:
```
    key <RCTL> {        [ Control_R               ]       };
    key <RWIN> {        [ Super_R             ]       };
```
Please let me know if you have any questions.

**Comment by petrstepanov** [comment]
Please refer to the solution above. Issue is fixed in the recent script version.
