### ISSUE TITLE
Close tab vs close window

### ISSUE THREAD

**Issue by nover** [petrstepanov/gnome-macos-remap#5]
First of all thanks for this awesome script, works like a charm :)

Except, it seems like cmd+w has been mapped to "close application" rather than "close window". At least in chromium and firefox it kills the entire app, rather than just closing the tab I'm in, which is the expected behavior of cmd+w on mac OS.

**Comment by entrinix** [comment]
Works great on Cinammon, it looks like cmd-w is close window though, and cmd-q is close application as in macOS.

**Comment by petrstepanov** [comment]
Addressed the issue. Please try installing the recent version. Think it works as intended now. Super+W closes the tab, Super+Q closes the window. Tested for Terminal app as well.

**Comment by petrstepanov** [comment]
> Works great on Cinammon, it looks like cmd-w is close window though, and cmd-q is close application as in macOS.

Cinnamon is built on top of Gnome 3 and utilizes `gsettings` therefore script will work at some point :-)

**Comment by adeebsal** [comment]
Not sure if this is intended behavior, but for Spotify and Discord which are both electron apps, Super/cmd+W doesn't close their windows. Super/cmd+Q completely closes the app as expected, but I'd like to have Discord running in the system tray in the background and while I could just click the close window button the keyboard shortcut is quicker.

**Comment by petrstepanov** [comment]
> I'd like to have Discord running in the system tray in the background

Thanks for pointing this out. Unfortunately macOS "[Close front window](https://support.apple.com/guide/macbook-air/keyboard-shortcuts-apd194062a6d/mac)" and GNOME's "[Close active window](https://wiki.gnome.org/Design/OS/KeyboardShortcuts#Applications)" work in a different way. Namely, in MacOS if application has a single window (no tabs) then "Close front window" closes the window, but keeps the application running. However in GNOME "Close active window" not just closes the window but kills the application too. This behavior is implemented in the GNOME's window manager and offf the top of my head I am not sure if this can be easily changed.

As a temporary solution you can explicitly tell window manager to **minimize** the front window (not close)  `Super/Cmd+M`. This hotkey will keep the Discord open but minimized in both OS. I have just added this functionality, so please re-install the script.

**Comment by petrstepanov** [comment]
> Not sure if this is intended behavior, but for Spotify and Discord which are both electron apps, Super/cmd+W doesn't close their windows

As an alternative solution I can recommend installing Discord and Spotify as progressive web apps. Here are couple ways of doing it.

###  Via Epiphany Browser
1. Install Epiphany browser `sudo apt-get install epiphany-browser`, open it and login to Discord/Spotify.
2. Under hamburger menu select "Install Site as Web Application..."
3. Launch your app from the menu.

### Via Chromium Browser
Same idea. Select menu → More tools → Create shortcut... Check "Open as window" checkbox.

Let me know if that helps!

**Comment by adeebsal** [comment]
These are both great workarounds, thanks! In truth I actually haven't used macOS in any large capacity before, so I'm not super familiar with some behavior. I'm considering getting a MacBook as my primary work machine when the next Apple Silicon ones launch and am trying to get familiar with the keybinds ahead of time. Your remap+scripts are perfect for that, especially paired with a few GNOME extensions and GTK theme, so thank you for creating this.

**Comment by petrstepanov** [comment]
> in chromium and firefox it kills the entire app, rather than just closing the tab I'm in

Hi Nicklas, sorry for late reply. Thanks for reporting the issue. I have recently resolved. Feel free to re-install the script and let me know if this thread can be closed.

**Comment by nover** [comment]
> > in chromium and firefox it kills the entire app, rather than just closing the tab I'm in
> 
> Hi Nicklas, sorry for late reply. Thanks for reporting the issue. I have recently resolved it. Feel free to re-install the script and let me know if this thread can be closed.

Hi @petrstepanov 

yes thanks! I have been following on the sidelines with the other discussions going on :) I will get around to testing it ASAP, I don't use the Ubuntu workstation quite as often as my macbook :)
