### ISSUE TITLE
Feature request: Wayland compatability

### ISSUE THREAD

**Issue by aioue** [petrstepanov/gnome-macos-remap#7]
Now that 21.04 uses Wayland by default.

**Comment by petrstepanov** [comment]
Unfortunately this remap script utilizes Autokey, which is an X11 application. [It does not seem possible to run Autokey on wayland yet](https://github.com/autokey/autokey/issues/87).

Alternative solution would be to replace Autokey with another remapper that works under Wayland. There are a few: [KeyMapper](https://github.com/sezanzeb/key-mapper), [Hawk](https://github.com/snyball/Hawck), [Waybind](https://github.com/arnarg/waybind). Wayland is more strict display server and none of the above programs seem to allow assigning application-specific keys. I recently tried KeyMapper (the one with the most Git stars) and did not manage to get it work stable enough.

I have Wayland on my radar and update this thread accordingly. Current version of the script will run on Ubuntu 21.04 if you [switch the display server to 'Xorg'](https://www.dropbox.com/s/4wgwzogdi7qmjvj/Screenshot%20from%202021-04-30%2021-20-24.png?dl=0).

**Comment by rbreaves** [comment]
Unless additional features are added to wayland I believe we, as developers, may be better off learning to communicate to the DE in question. That is more work for us devs though, since we'd then need to support separate DE's instead of a single backend like x11 or wayland. I did do some tests already on doing that with Gnome DE under wayland specifically and the xkeysnail project, but the performance and reliability was not good.

I posted my findings over at xkeysnail - but unless someone chimes and/or finds a better way I am stuck as well with my kinto project.

**Comment by petrstepanov** [comment]
I agree. Recently I've tried implementing this remap in Wayland with [https://github.com/sezanzeb/key-mapper](https://github.com/sezanzeb/key-mapper). However, it was not running stable enough.

**Comment by petrstepanov** [comment]
For those who are interested, a very early Wayland compatible version with limited number of keybindings is published here https://github.com/petrstepanov/gnome-macos-remap-wayland. I am sure we will have a solid Wayland solution early 2021.

**Comment by olosegres** [comment]
JFYI 
There is [xremap](https://github.com/k0kubun/xremap) appears, and author claims that it is faster
> Xremap is written in Rust, which is faster than JIT-less interpreters like Python.

**Comment by ameeno** [comment]
> JFYI There is [xremap](https://github.com/k0kubun/xremap) appears, and author claims that it is faster
> 
> > Xremap is written in Rust, which is faster than JIT-less interpreters like Python.

Oooh, this looks nice, multi-wm (xorg+wayland) and simple config via toml/yaml!!!!

any mac keyconfigs for Xremap? :)

**Comment by petrstepanov** [comment]
@olosegres thank you for pointing out the `xremap`. It seems to be a promising solution. I tried it a few times and was not able to get it working on Fedora 36 with Gnome 42.1. It might take some time to get things working stable.

@ameeno meanwhile you can replace your display manager with an antique one. If you want to help things move quicker feel free to to test this `xremap` [issue](https://github.com/k0kubun/xremap/issues/88) on your Fedora.

**Comment by petrstepanov** [comment]
Update for the Wayland solution with `xremap`. I attempted to implement the remap with with `xremap` program but [ran into an issue](https://github.com/k0kubun/xremap/issues/100) with modifier key combinations. I'll publish a Wayland solution after the issue is resolved.

**Comment by petrstepanov** [comment]
Just published version for wayland here: https://github.com/petrstepanov/gnome-macos-remap-wayland
