### ISSUE TITLE
switching between tabs firefox/chrome

### ISSUE THREAD

**Issue by gagomes** [petrstepanov/gnome-macos-remap#8]
In OSX, ctrl-tab and ctrl-shift-tab cycle forward/backward over the browser tabs. Is it possible to get this with the gnome-macos-remap? It's the only snag I've found so far, since as a tab hoarder, it saves a lot of time!

**Comment by petrstepanov** [comment]
Thanks for bringing this up. Just pushed the change. It seems to work just fine now.

**Comment by gagomes** [comment]
Hi @petrstepanov  - that was surprisingly fast response and feature improvement, I'm impressed. I verified it to be working on Ubuntu 20.04 with firefox and chromium. Closing. :+1:

**Comment by joseph-zhong** [comment]
Hi @petrstepanov, thanks for this awesome application

I was wondering if this was tested in Ubuntu 22? I just did a fresh install and noticed the only way for me to switch tabs (on Chrome, and tested on Firefox) was CMD-Tab

ctrl-tab switches between applications it seems

**Comment by petrstepanov** [comment]
Hi @joseph-zhong thank you for reaching out. I just tested a clean install on Ubuntu 22.04 LTS and tabs are switching fine for me. There may be some issues if you overrided some keyboard settings in Tweaks? Please confirm that your keyboard settings in Tweaks correspond to the screenshots below:

![Screenshot from 2022-05-15 11-34-04](https://user-images.githubusercontent.com/859814/168481282-80bfa898-5a4a-47f5-b939-1f545aac4a37.png)

![Screenshot from 2022-05-15 11-34-15](https://user-images.githubusercontent.com/859814/168481295-726c30ef-c409-4e1c-9703-4988788701ad.png)

![Screenshot from 2022-05-15 11-34-22](https://user-images.githubusercontent.com/859814/168481300-8e0f8e06-0e85-4d0b-9005-557ec6a665db.png)

Looking forward to hearing from you!
