### ISSUE TITLE
Is there a way to prevent flipping Super and Control keys in the terminal?

### ISSUE THREAD

**Issue by Misaka13514** [petrstepanov/gnome-macos-remap#9]
I need to use some shortcut keys of vim in the terminal, such as visual block editing.

Currently I cannot use `Ctrl+V` because Control and Super are flipped. The `Windows+V` obviously conflicts with the paste operation.

Many commonly used shortcut keys cannot be used as well, such as `Ctrl+Z`.

**Comment by petrstepanov** [comment]
@Misaka13514 this is a very good question. I expected someone asking it. I just overrided some `Ctrl+<letter>` combinations for the Terminal, including your `Ctrl+V` and `Ctrl+Z`. Please give it a try and Let me know how it works for you.

**Comment by Misaka13514** [comment]
Thank you @petrstepanov , although this is not a perfect solution, I think it can be used for the time being.

**Comment by petrstepanov** [comment]
@Misaka13514 I highly doubt it is possible to achieve a perfection with this remapping task. In the end of the day if "it works" it does not necessarily has to be implemented in a "beautiful way".

**Comment by Misaka13514** [comment]
> it does not necessarily has to be implemented in a "beautiful way".

That's true.
